### ISSUE TITLE
Add manifest to make app "installable"

### ISSUE THREAD

**Issue by psydvl** [jarvis394/habra#25]
There are manuals: 
[developer.mozilla.org en](https://developer.mozilla.org/en/docs/Web/Progressive_web_apps/Installable_PWAs)
[developer.mozilla.org ru](https://developer.mozilla.org/ru/docs/Web/Progressive_web_apps/Installable_PWAs)
[web.dev](https://web.dev/add-manifest/)
[habr.com](https://habr.com/p/275849/)

**Comment by jarvis394** [comment]
Anyways, you can install the app by adding it as a shortcut on home screen. (Chrome:  three dots -> Add to Home screen). But without a manifest it will lead to no icon being shown and wrong startup path opened.

Will be soo implemented.

**Comment by psydvl** [comment]
For now, it opens up in a new browser tab. 
With manifest, it will be loaded as a separate app and shows individually in the "Recent apps" activity on Android. You can see this behavior on https://habr.com.

**Comment by jarvis394** [comment]
@psydvl should be fixed with the latest commit (2b332b3b26c116e011cf5a11aa57bd95be8a10bf)

**Comment by psydvl** [comment]
Still not meet all [web app manifest requirements](https://web.dev/installable-manifest):
- [x] A short_name or name property
- [ ] An icons property that includes a 192x192 px and a 512x512 px icon
- [x] A start_url property
- [x] A display property set to fullscreen, standalone, or minimal-ui
- [ ] A prefer_related_applications property set to a value other than true.

Also, Chrome DevTools Lighthouse reports the error.

**Comment by jarvis394** [comment]
meh, these requirements are not strict. You might not have certain parameters and icons and still have the ability to add an app on Home screen and it will have a nice icon.

**Comment by psydvl** [comment]
I think the difference is distinguishable.
![gif difference](https://user-images.githubusercontent.com/43755002/98078266-d26ef180-1e82-11eb-8278-797333003b87.gif)
